project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "MESM Math Bootcamp"

  announcement: 
    icon: hammer
    dismissable: true
    content: "This wesbite is under construction."
    type: primary
    position: below-navbar  

  navbar:
    right:
      - href: index.qmd
        text: 🗺️ home
      - text: 📓 notes
        href: notes/about.qmd

      - icon: github
        menu:
          - text: Source code
            url: https://github.com/MESM-math-bootcamp/MESM-math-bootcamp-website
          - text: Report a bug
            url: https://github.com/MESM-math-bootcamp/MESM-math-bootcamp-website/issues

  sidebar:
    - id: notes
      contents:
        - notes/about.qmd
        - notes/day1_algebra.qmd
        - notes/day2_limits.qmd
        - notes/day3_derivatives.qmd
        - notes/day4_integrals.qmd
        - notes/day5_differential_equations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



