project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Bren Calculus Workshop"
  page-footer: 
    right: This website is built with [Quarto](https://quarto.org/) and [GitHub pages](https://github.com/MEDS-eds-220/MEDS-eds-220-course).

  announcement: 
    icon: hammer
    dismissable: true
    content: "This wesbite is under construction."
    type: primary
    position: below-navbar  

  navbar:
    right:

      - icon: github
        menu:
          - text: Source code
            url: https://github.com/MESM-math-bootcamp/MESM-math-bootcamp-website
          - text: Report a bug
            url: https://github.com/MESM-math-bootcamp/MESM-math-bootcamp-website/issues

  sidebar:
    contents:
      - index.qmd
      - notes/day1_algebra.qmd
      - notes/day2_limits.qmd
      - notes/day3_derivatives.qmd
      - notes/day4_integrals.qmd
      - notes/day5_differential_equations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



