---
title: "Bren Math Workshop"
subtitle: "Master of Environmental Science and Management (MESM)"
description: "Summer 2026"
title-block-banner: false
toc: false
---

Welcome to the course materials for the Bren Math Workshop! In this website you will find all the materials for the Summer 2026 session. This workshop is part of the [UCSB Master of Environmental Science and Management](https://bren.ucsb.edu/masters-programs/master-environmental-science-and-management) at the [Bren School of Environmental Science and Management](https://bren.ucsb.edu).

## Workshop description

This 5-day workshop takes place during the MESM orientation week for incoming students. This workshop is meant to get everyone to a sufficient level to excel in all the courses offered at Bren.
The primary workshop objectives are as follows:

- Reinforce math skills used in Bren courses
- Understand how math and calculus are used in environmental science
- Help transition to graduate school life
- Build collaborative environment

## Instructor
[**Carmen Galaz García**](https://bren.ucsb.edu/people/carmen-galaz-garcia-0) (she/her/hers)

- E-mail: c_galazgarcia@ucsb.edu
- Student hours: By appointment or right after the sessions end

<!-- ## Syllabus

[Click here to see the syllabus.](https://docs.google.com/document/d/14dcg7u3n1rEz-fReZcO8Gnddk3hEGi8u4DKTroWdonU/edit?usp=share_link){target="_blank"}   -->

## Acknowledgements

The materials for the Bren Math Workshop were originally developed and taught by [Nathan Grimes](https://bren.ucsb.edu/people/nathan-grimes). This new website houses materials which are reused, adapted, and expanded from, and inspired by the previous instructors' work.


<!-- [Allison Horst](https://allisonhorst.github.io/){target="_blank"}. It has since been taught and adapted by [Ruth Oliver](https://www.oliverlab.org){target="_blank"}, [Sam Shanny-Csik](https://samanthacsik.github.io){target="_blank"} and, most recently, myself, [Carmen Galaz García](https://bren.ucsb.edu/people/carmen-galaz-garcia).  -->