{
  "hash": "5ad90fc0b44f44417dee8a1fc0904a10",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat:\n  revealjs:\n    slide-number: true\n    # code-link: true\n    highlight-style: a11y\n    chalkboard: true\n    theme:\n      - ../../ucsb-media.scss\n    include-in-header:\n      text: |\n        <script>\n        (function loadCancelExtension(){\n          if (window.MathJax && window.MathJax.Hub) {\n            MathJax.Hub.Config({ TeX: { extensions: [\"cancel.js\"] } });\n          } else {\n            setTimeout(loadCancelExtension, 20);\n          }\n        })();\n        </script>\neditor_options:\n  chunk_output_type: console\n---\n\n## {#title-slide data-menu-title=\"Title Slide\" background=\"#053660\"}\n\n[Day 4: Bren Math Workshop]{.custom-title}\n\n<hr class=\"hr-teal\">\n\n[Carmen Galaz García, Ph.D.]{.body-text-l .center-text .baby-blue-text}\n\n[Bren School of Environmental Science & Management]{.center-text .body-text-m .baby-blue-text}\n\n<br>\n\n---\n\n## {#interpreting-slope data-menu-title=\"Interpreting the slope title\" background-color=\"#003660\"}\n\n\n<div class=\"page-center\">\n<div class=\"custom-subtitle\">Interpreting the slope</div>\n</div>\n\n---\n\n## {#avg-rate-of-change-blank data-menu-title=\"Slope (average)\"}\n\n[Slope (average)]{.slide-title}\n\n<hr>\n\n::::{.columns}\n:::{.column width=\"50%\"}\n\n::: {.body-text-m}\nSometimes, it can be useful to find the **average rate of change** of a function.\n:::\n\n✏️\n\n:::\n\n:::{.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n::::\n\n---\n\n## {#avg-rate-of-change data-menu-title=\"Slope (average)\"}\n\n[Slope (average)]{.slide-title}\n\n<hr>\n\n::::{.columns}\n:::{.column width=\"50%\"}\n\n::: {.body-text-m}\nSometimes, it can be useful to find the **average rate of change** of a function.\n\nBetween any two points $(x_1,y_1)$ and $(x_2,y_2)$  on the graph of a function, the slope is found by:\n\n<br>\n\n$$m=\\frac{\\Delta y}{\\Delta x}=\\frac{y_2-y_1}{x_2-x_1}$$\n\nSame idea as in a line!\n:::\n\n:::\n\n:::{.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n::::\n\n---\n\n## {#slope-roc data-menu-title=\"Slope represents rate of change\"}\n\n[Slope represents rate of change]{.slide-title}\n\n<hr>\n\nIce-core data before 1958. Mauna Loa data after 1958. \n\n![Source:[The Keeling Curve](https://keelingcurve.ucsd.edu)](../_linear-functions/images/loa.PNG)\n\n---\n\n## {#practice-out-loud data-menu-title=\"Practice out loud\"} \n\n[Get into the practice of saying the meaning out loud]{.slide-title3}\n\n<hr>\n\n- As if you're explaining it to someone unfamiliar with the data\n- Including units\n- Without overstating certainty \n\n[**For example:**]{.body-text-m} \n\n>\"Between 1972 and 2020 the price of hobbit homes increased by an average of $2,450 per year\" \n\n<br>\n\n*differs from*\n\n<br>\n\n>\"Between 1972 and 2020 the price of hobbit homes increased by $2,450 per year.\" \n\n---\n\n## {#slope-practice data-menu-title=\"Slope practice\" .smaller} \n\n[Slope practice]{.slide-title3}\n\n<hr>\n\n:::{style=\"color:green;\"}\n✏️ A community air-quality monitoring group tracked the additional fine particulate matter concentration, $P(t)$ (µg/m³ of PM2.5 above baseline), in the neighborhood's air over 20 days of a construction phase.\n:::\n\n:::: {.columns}\n::: {.column width=\"35%\"}\n\n:::{style=\"color:green;\"}\n| $t$ (days) | $P(t)$ (µg/m³) |\n|:---:|:---:|\n| 2  | 14.4 |\n| 6  | 33.6 |\n| 10 | 40.0 |\n| 14 | 33.6 |\n| 18 | 14.4 |\n:::\n:::\n\n::: {.column width=\"65%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=95%}\n:::\n:::\n\n:::\n::::\n\n:::{style=\"color:green;\"}\na) Calculate the average rate of change in additional PM2.5 concentration between day 2 and day 6. Represent this graphically on the plot.\nb) Write your answer as a full sentence, with units, without overstating certainty.\n:::\n\n---\n\n## {#slope-practice-blank data-menu-title=\"Slope practice\"} \n\n[Slope practice]{.slide-title3}\n\n<hr>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n:::{style=\"color:green;\" }\n:::{.body-text-s}\n$P(t)$ measures µg/m³ of PM2.5 above baseline in the neighborhood's air over the 20 days of that construction phase.\n:::\n\n| $t$ (days) | $P(t)$ (µg/m³) |\n|:---:|:---:|\n| 2  | 14.4 |\n| 6  | 33.6 |\n| 10 | 40.0 |\n| 14 | 33.6 |\n| 18 | 14.4 |\n\n\na) Calculate the average rate of change in additional PM2.5 concentration between day 2 and day 6. Represent this graphically on the plot.\nb) Write your answer as a full sentence, with units, without overstating certainty.\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=95%}\n:::\n:::\n\n✏️ \n\n:::\n\n:::\n\n---\n\n## {#slope-practice-solution data-menu-title=\"Slope practice\"} \n\n[Slope practice]{.slide-title3}\n\n<hr>\n\n<br>\n \n a)\n$$\n\\text{average rate of change} = \\frac{P(6) - P(2)}{6-2} = \\frac{33.6 - 14.4}{4} = \\frac{19.2}{4} = 4.8 \\ \\frac{\\mu\\text{g/m}^3}{\\text{day}}\n$$\n\n<br>\n\nb) Between day 2 and day 6 of the grading phase, additional PM2.5 concentration in the  neighborhood increased by an average of 4.8 µg/m³ per day.\n\n\n---\n\n## {#whole-story data-menu-title=\"Whole story\"} \n\n[The *average* slope of a continuous function rarely tells the whole story]{.slide-title3}\n  \n<hr>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/cod_graph.jpg){fig-align='center' width=100%}\n:::\n:::\n\n\n\n---\n\n## {#slope-avg cdata-menu-title=\"can be average or instantaneous\"}\n\n[Slope can be *average* or *instantaneous*]{.slide-title}\n\n<hr>\n\n::::{.columns}\n:::{.column width=\"50%\"}\n\n\n- Rise over run can always be used to find average rate of change between two parts of a graph\n\n\n:::\n\n:::{.column width=\"50%\"}\n\n- Instantaneous rate of change leads us to ✨calculus✨.\n\n:::\n::::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/trex.PNG){fig-align='center' width=50%}\n:::\n:::\n\n\n\n---\n\n## {#limits-title data-menu-title=\"Logarithms\" background-color=\"#003660\"}\n\n\n<div class=\"page-center\">\n<div class=\"custom-subtitle\">Limits</div>\n</div>\n\n---\n\n## {#limits-blank data-menu-title=\"Limits\"}\n\n[Limits]{.slide-title}\n\n<hr>\n\n✏️\n\n\n\n---\n\n## {#limits data-menu-title=\"Limits\"}\n\n[Limits]{.slide-title}\n\n<hr>\n\n**Definition**\n\nWe say a number $L$ is the limit of a function $f(x)$ as its variable $x$ approaches a number $c$, if the function's output values $f(x)$ approach $L$ when $x$ get closer to $c$. \n\n<br>\n\nWe write this symbolically as:\n\n$$\n\\large\n\\lim_{x\\to c} f(x)=L\n$$\n\n<br>\n\nWe read this as: [\"The limit of $f(x)$ as $x$ approaches $c$ is $L$.\"]{.teal-text}\n\n---\n\n## {#lim-ex-blank data-menu-title=\"Limit Example\"}\n\n[Limits example: numerical]{.slide-title}\n\n<hr>\n\nWhat is the limit of $f(x)=2x^2-4$ as $x$ approaches 2?\n\nWe need to examine the values of $f(x)$ as $x$ gets closer to 2 from both sides.\n\n![](images/limits-blank.png){fig-align=\"center\" width=\"50%\"}\n\n✏️\n\n<br>\n<br>\n<br>\n\n---\n\n## {#lim-ex-3 data-menu-title=\"Limit Example\"}\n\n[Limits example: numerical]{.slide-title}\n\n<hr>\n\nWhat is the limit of $f(x)=2x^2-4$ as $x$ approaches 2?\n\nWe need to examine the values of $f(x)$ as $x$ gets closer to 2 from both sides.\n\n\n![](images/limits.PNG){fig-align=\"center\" width=\"70%\"}\n\n\nFrom both directions it looks like $f(x)$ converges to 4.\n\nSo, we say that [\"The limit of $2x^2-4$ as $x$ approaches 2 is 4\"]{.teal-text}. We can write it like this:\n\n$$\n\\lim_{x\\to 2}(2x^2-4)=4\n$$\n\n---\n\n## {#limit-graph-sol data-menu-title=\"Graphical Solution\"}\n\n[Limits example: graph]{.slide-title}\n\n<hr>\n\nWhat is the limit of $f(x)=2x^2-4$ as $x$ approaches 2?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/limits-graph.png){fig-align='center' width=200%}\n:::\n:::\n\n\nFrom both directions it looks like $f(x)$ converges to 4.\n\nSo, $\\lim_{x\\to 2}(2x^2-4)=4$.\n\n---\n\n## {#intro-derv data-menu-title=\"Introduction to Derivates\" background-color=\"#003660\"}\n\n<div class=\"page-center\">\n<div class=\"custom-subtitle\">Introduction to derivatives</div>\n</div>\n\n---\n\n## {#average-slope data-menu-title=\"Average slope\"}\n\n[Average slope]{.slide-title}\n\n<hr>\n\n<div style=\"position: absolute; bottom: 550px; right: 1000px; font-size: 1em;\">                                                                               \n  ✏️                    \n</div>  \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=960}\n:::\n:::\n\n\nStart with:\n\n\n<br>\n\nNearby point:\n\n<br>\n\nAverage slope:\n\n---\n\n## {#average-slope-filled data-menu-title=\"Average slope\"}\n\n[Average slope]{.slide-title}\n\n<hr>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=960}\n:::\n:::\n\n\nStart with a point $(x,f(x))$ on the graph. \n\nA nearby point can be $(x+\\Delta x, f(x+\\Delta x))$, where $\\Delta x$ is a short distance from $x$. \n\n\n<br>\n\nThe average slope between $(x,f(x))$ and $(x+\\Delta x, f(x+\\Delta x))$ is given by\n\n<span style=\"color:red\">\n$$\\text{average slope} = \\frac{f(x+\\Delta x) - f(x)}{(x+\\Delta x)-x} = \\frac{f(x+\\Delta x) - f(x)}{\\Delta x}.$$\n</span>\n\n**What happens when $\\Delta x$ becomes smaller and smaller?**\n\n---\n\n## {#walkthrough-1 data-menu-title=\"Walkthrough\"}\n\n[What happens when $\\Delta x \\to 0$?]{.slide-title}\n\n<hr>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n---\n\n## {#walkthrough-2 data-menu-title=\"Walkthrough\"}\n\n[What happens when $\\Delta x \\to 0$?]{.slide-title}\n\n<hr>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n---\n\n## {#walkthrough-3 data-menu-title=\"Walkthrough\"}\n\n[What happens when $\\Delta x \\to 0$?]{.slide-title}\n\n<hr>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n---\n\n## {#walkthrough-4 data-menu-title=\"Walkthrough\"}\n\n[What happens when $\\Delta x \\to 0$?]{.slide-title}\n\n<hr>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n---\n\n## {#tangent data-menu-title=\"Tangent Lines\"}\n\n[Tangent lines]{.slide-title}\n\n<hr>\n\n**What if we let $\\Delta x=0$?**\n\nThen we would have the slope of a line that only touches the graph at exactly $(x, f(x))$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-slides_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::{.center-text .teal-text}\nThese very special types of lines are called **tangent lines**.\n:::\n---\n\n## {#recap-1 data-menu-title=\"Recap in math notation\"}\n\n[Derivative definition]{.slide-title}\n\n<hr>\n\nRemember the slope of the line that passes between two points $(x_1, y_1)$ and $(x_2, y_2)$ is:\n\n$$\\text{slope}=\\frac{y_2-y_1}{x_2-x_1}.$$\n\n---\n\n## {#recap-2 data-menu-title=\"Recap in math notation\"}\n\n[Derivative definition]{.slide-title}\n\n<hr>\n\nRemember the slope of the line that passes between two points $(x_1, y_1)$ and $(x_2, y_2)$ is:\n\n$$\\text{slope}=\\frac{y_2-y_1}{x_2-x_1}.$$\n\n\nIf we have a function $f(x)$, then $(x,f(x))$ represents a point on its graph.\n\n\nChoose a different point on the graph that is $\\Delta x$ away: $(x+\\Delta x,f(x+\\Delta x))$.\n\n---\n\n## {#recap-3 data-menu-title=\"Recap in math notation\"}\n\n[Derivative definition]{.slide-title}\n\n<hr>\n\nRemember the slope of the line that passes between two points $(x_1, y_1)$ and $(x_2, y_2)$ is:\n\n$$\\text{slope}=\\frac{y_2-y_1}{x_2-x_1}.$$\n\n\nIf we have a function $f(x)$, then $(x,f(x))$ represents a point on its graph.\n\n\nChoose a different point on the graph that is $\\Delta x$ away: $(x+\\Delta x,f(x+\\Delta x))$.\n\n\nPlug these points on the graph of $f(x)$ into the slope equation:\n\n$$\n\\text{slope}=\\frac{f(x+\\Delta x)-f(x)}{\\Delta x}.\n$$\n\n---\n\n## {#recap-4 data-menu-title=\"Recap in math notation\"}\n\n[Derivative definition]{.slide-title}\n\n<hr>\n\nRemember the slope of the line that passes between two points $(x_1, y_1)$ and $(x_2, y_2)$ is:\n\n$$\\text{slope}=\\frac{y_2-y_1}{x_2-x_1}.$$\n\n\nIf we have a function $f(x)$, then $(x,f(x))$ represents a point on its graph.\n\n\nChoose a different point on the graph that is $\\Delta x$ away: $(x+\\Delta x,f(x+\\Delta x))$.\n\n\nPlug these points on the graph of $f(x)$ into the slope equation:\n\n$$\n\\text{slope}=\\frac{f(x+\\Delta x)-f(x)}{\\Delta x}.\n$$\n\nWhen we let $\\Delta x \\to 0$ we get <span style=\"color:red\">**the slope of the tangent line at $x$**</span>\n\n<span style=\"color:red\">\n$$\n\\large\nf'(x)=\\lim_{\\Delta x \\to 0} \\frac{f(x+\\Delta x)-f(x)}{\\Delta x}\n$$\n</span>\n\n<span style=\"color:red\">**This is the derivative of $f$ at $x$.**</span>\nAlso denoted $\\frac{df}{dx}$. \n\n\n---\n\n## {#deriv9 data-menu-title=\"Derivative\"} \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/derivative_9.jpg){fig-align='center' width=100%}\n:::\n:::\n\n\n::: {.footer}\n*Artwork by [Allison Horst](https://allisonhorst.com/)*\n:::\n\n---\n\n## {#calc data-menu-title=\"Calculus and Derivatives are the study of change\"}\n\n[Calculus and derivatives are used to study change]{.slide-title}\n\n<hr>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/trex-no-labels.PNG){fig-align='center' width=75%}\n:::\n:::\n\n\n---\n\n## {#envs-change3 data-menu-title=\"Enviromental Science is the Study of Change\"}\n\n[Environmental Science studies change]{.slide-title}\n\n<hr>\n\n![](images/bait.jpeg){fig-align=\"center\"}\n\n<br>\n\n[🤔 Talk with a partner, what are 2 fields of environmental science where studying the rate of change and derivatives would be important?]{style=\"color:green;\"}\n\n---\n\n## {#break data-menu-title=\"10 minute break\"}\n\n[Let's take a 10 minute break]{.slide-title}\n\n<hr>\n\n![image: Flaticon.com](../day2_functions_graphs/images/coffee-break.png)\n\n---\n\n## {#interpretation-derv data-menu-title=\"Introduction to Derivates\" background-color=\"#003660\"}\n\n<div class=\"page-center\">\n<div class=\"custom-subtitle\">Interpreting the derivative</div>\n</div>\n\n---\n\n## {#fx-and-fprimeofx data-menu-title=\"Relationship between functions and their derivatives\"}\n\n[Relationship between functions and their derivatives]{.slide-title}\n\n<hr>\n\n![](images/deriviative-interpretation-2.png)\n\nRemember: $f'(x) = \\frac{df}{dx}$ is the derivative of $f(x)$. Same thing, different notation!\n\n---\n\n## {#units-of-derivative-blank data-menu-title=\"Units of the Derivative\"}\n\n[Units of the derivative]{.slide-title}\n\n<hr>\n\nIf we have a function $f(x)$, then \n\n<br>\n<br>\n<br>\n\n$f'(x)$ is approximately equal to the change in $f(x)$ when the variable $x$ increases by 1 unit.\n\n<br>\n\n:::{style=\"color:green;\"}\n✏️ **Example:**\n:::\n\n- $g(t)=$ temperature in degrees Celsius at $t$ hours after midnight\n- $g(7)=15$ means \n- $g'(7)=3$ means \n- $g'(7)=-2$ means\n\n---\n\n## {#units-of-derivative data-menu-title=\"Units of the Derivative\"}\n\n[Units of the derivative]{.slide-title}\n\n<hr>\n\nIf we have a function $f(x)$, then \n\n:::{.center-text .teal-text}\nthe units for $f'(x)$ are the units of $f(x)$ divided by the units of $x$.\n:::\n\n<br>\n\n$f'(x)$ is approximately equal to the change in $f(x)$ when the variable $x$ increases by 1 unit.\n\n<br>\n\n:::{style=\"color:green;\"}\n✏️ **Example:**\n:::\n\n- $g(t)=$ temperature in degrees Celsius at $t$ hours after midnight\n- $g(7)=15$ means the temperature is 15°C at 7 hours after midnight (7 am)\n- $g'(7)=3$ means the temperature is increasing at a rate of 3°C/ hour at 7am\n- $g'(7)=-2$ means the temperature is decreasing at a rate of 2°C/hour at 7am\n\n---\n\n## {#units-of-derivative-exercise data-menu-title=\"Units of the Derivative\"}\n\n[Units of the derivative]{.slide-title}\n\n<hr>\n\n:::{style=\"color:green;\"}\n✏️\n\nThe cost of extracting $T$ tons of ore from a copper mine is $C = f(T)$ dollars. What does it mean to say that $f'(2000) = 100$?\n\nWrite your answer as a full sentence, with units.\n:::\n\n---\n\n## {#units-of-derivative-solution data-menu-title=\"Units of the Derivative\"}\n\n[Units of the derivative]{.slide-title}\n\n<hr>\n\n:::{style=\"color:green;\"}\n✏️\n\nThe cost of extracting $T$ tons of ore from a copper mine is $C = f(T)$ dollars. What does it mean to say that $f'(2000) = 100$?\n\nWrite your answer as a full sentence, with units.\n:::\n\n- Units of $f'$ are dollars per ton, so $f'(2000) = 100$ dollars per ton.\n\n- When 2000 tons have been extracted, the cost of extraction increases at a rate of $100 per ton.\n\n\n- When 2000 tons of ore have already been extracted from the mine, the cost of extracting the next ton is approximately $100 more.\n\n---\n\n## {#sign-of-derivative-blank data-menu-title=\"Tangent lines to f(x)=x^2\"}\n\n[Sign of the derivative]{.slide-title}\n\n<hr>\n\n <div style=\"position: absolute; bottom: 560px; right: 1000px; font-size: 1em;\">                                                                               \n✏️                    \n  </div>  \n\n- If the **derivative is positive**, it means the rate of change is positive, and the function is increasing. \n\n<br>\n<br>\n\n- If the **derivative is negative**, it means the rate of change is negative, and the function is decreasing. \n\n<br>\n<br>\n\n- If the **derivative is zero**, it means the rate of change is zero, and the function is neither increasing nor decreasing (it **may be at a local maximum or minimum**).\n\n---\n\n## {#sign-of-derivative data-menu-title=\"Tangent lines to f(x)=x^2\"}\n\n[Sign of the derivative]{.slide-title}\n\n<hr>\n\n- If the **derivative is positive**, it means the rate of change is positive, and the function is increasing. \n\n$$f'(a) > 0 \\implies \\text{function is increasing near } a$$\n\n- If the **derivative is negative**, it means the rate of change is negative, and the function is decreasing. \n\n$$f'(a) < 0 \\implies \\text{function is decreasing near } a$$\n\n- If the **derivative is zero**, it means the rate of change is zero, and the function is neither increasing nor decreasing (it **may be at a local maximum or minimum**).\n\n---\n\n## {#sign-of-derivative-practice data-menu-title=\"Tangent lines to f(x)=x^2\"}\n\n[Sign of the derivative practice]{.slide-title}\n\n<hr>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n:::{style=\"color:green;\"}\n✏️ \n\n(1) Determine for which sections of the graph of $f(x)$ the derivative is positive, negative, or zero.\n:::\n:::\n\n\n::: {.column width=\"50%\"}\n![](images/sign-of-derivative-1.png)\n:::\n\n:::\n\n---\n\n## {#sign-of-derivative-practice-2 data-menu-title=\"Tangent lines to f(x)=x^2\"}\n\n[Sign of the derivative practice]{.slide-title}\n\n<hr>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n:::{style=\"color:green;\"}\n✏️ \n\n(1) Determine for which sections of the graph of $f(x)$ the derivative is positive, negative, or zero.\n\n<br>\n<br>\n\n(2) *Example:* Sketch a graph for the derivative.\n:::\n:::\n\n::: {.column width=\"50%\"}\n![](images/sign-of-derivative-2.png)\n:::\n\n:::\n\n---\n\n## {#sign-of-derivative-practice-3 data-menu-title=\"Tangent lines to f(x)=x^2\"}\n\n[Sign of the derivative practice]{.slide-title}\n\n<hr>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n:::{style=\"color:green;\"}\n✏️ \n\n(1) Determine for which sections of the graph of $f(x)$ the derivative is positive, negative, or zero.\n\n<br>\n<br>\n\n(2) *Example:* Sketch a graph for the derivative.\n:::\n:::\n\n::: {.column width=\"50%\"}\n![](images/sign-of-derivative-3.png)\n:::\n\n:::\n\n---\n\n## {#application data-menu-title=\"Logistic growth\"}\n\n[Application: Logistic growth]{.slide-title}\n\n<hr>\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\nIn logistic growth, the population $N$ grows rapidly at first, but then slows down as it approaches a maximum population size $K$, called the carrying capacity.\n\n:::{style=\"color:green;\"}\n✏️ \n\n(1) What does it mean that $\\frac{dN}{dt}$ is positive, negative, or zero in terms of the population growth?\n\n(2) When do you think $\\frac{dN}{dt}$ is positive, negative, or zero?\n\n(3) When is population growth fastest?\n:::\n:::\n\n\n::: {.column width=\"50%\"}\n![](images/logistic-growth.png)\n:::\n\n:::\n\n---\n\n## {#application-solution data-menu-title=\"Logistic growth\" .smaller}\n\n[Application: Logistic growth]{.slide-title}\n\n<hr>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n(1) $\\frac{dN}{dt}>0$ means the population is growing; $\\frac{dN}{dt}<0$ means the population is shrinking; $\\frac{dN}{dt}=0$ means the population size is momentarily unchanged.\n\n<br>\n\n(2) $\\frac{dN}{dt}$ is **positive** for all $0<N<K$, since the population is always increasing toward the carrying capacity. $\\frac{dN}{dt}$ is **zero** at $N=0$ and $N=K$, the two points where the population stops changing.\n\n<br>\n\n(3) Population growth is **fastest** at $N=K/2$, the inflection point of the curve, where the slope of $N(t)$ is steepest.\n\n:::\n\n::: {.column width=\"50%\"}\n![](images/logistic-growth.png)\n:::\n\n:::\n\n---\n\n## {#diff-rules data-menu-title=\"Introduction to Derivates\" background-color=\"#003660\"}\n\n<div class=\"page-center\">\n<div class=\"custom-subtitle\">Rules for differentiation</div>\n</div>\n\n\n---\n\n## {#diff-rules-1-blank data-menu-title=\"Rules for Differentiation (1)\"}\n\n[Rules for differentiation (1)]{.slide-title}\n\n<hr>\n\n**Constant Rule** ✏️\n\n\n\n<br>\n<br>\n<br>\n<br>\n<br>\n<br>\n\n\n**Power Rule** ✏️\n\n---\n\n## {#diff-rules-1 data-menu-title=\"Rules for Differentiation (1)\"}\n\n[Rules for differentiation (1)]{.slide-title}\n\n<hr>\n\n**Constant Rule**\n\nLet $c$ be a constant (so, a number). If $f(x) = c$, then $f'(x)=0$. Equivalently\n\n$$\\frac{d}{dx}c = 0$$\n\n\n\n**Power Rule**\n\nLet $n$ be a (real) number, if $f(x)= x^n$, then $f'(x) = nx^{n-1}$. Equivalently\n$$\n\\frac{d}{dx}[x^n]\n=nx^{n-1}.\n$$\n\n**Examples**   ✏️\n\n$$\n\\begin{align}\n&y=100 & &f(x)=x^5 & &f(x)=\\frac{1}{x^2}\n\\end{align}\n$$\n\n---\n\n## {#diff-rules-2-blank data-menu-title=\"Rules for Differentiation (2)\"}\n\n[Rules for differentiation (2)]{.slide-title}\n\n<hr>\n\n**Sum and Difference Rules**\n\n✏️\n\n---\n\n## {#diff-rules-2 data-menu-title=\"Rules for Differentiation (2)\" .smaller}\n\n[Rules for differentiation (2)]{.slide-title}\n\n<hr>\n\n**Sum and Difference Rules**\n\nLet $f(x)$ and $g(x)$ be differentiable functions. Then \n\n$$\n\\begin{align}\n\\frac{d}{dx}[f(x)+g(x)]=\\frac{d}{dx}f(x)+\\frac{d}{dx}g(x) \\\\\n\\frac{d}{dx}[f(x)-g(x)]=\\frac{d}{dx}f(x)-\\frac{d}{dx}g(x)\n\\end{align}\n$$\n\n\n😵*All this says is: if the function has pieces that are added or subtracted you can take the derivative of each individual piece and add those derivatives.*\n\nThe $\\frac{d}{dx}$ notation can be a lot here, the prime notation is a bit better:\n\n$$\n\\begin{align}\n[f(x)+g(x)]'=f'(x)+g'(x) \\\\\n[f(x)-g(x)]'=f'(x)-g'(x)\n\\end{align}\n$$\n\n\n✏️ **Example** \n\n$$\nf(x)=x^3-x^2-15\n$$\n\n---\n\n## {#diff-rules-3-blank data-menu-title=\"Rules for Differentiation (3)\"}\n\n[Rules for differentiation (3)]{.slide-title}\n\n<hr>\n\n**Constant Multiplier Rule**\n\n✏️\n\n---\n\n## {#diff-rules-3-example data-menu-title=\"Rules for Differentiation (3)\".smaller}\n\n[Rules for differentiation (3)]{.slide-title}\n\n<hr>\n\n**Constant Multiplier Rule**\n\nThe derivative of a constant $c$ multiplied by a function $f(x)$ is the same as the constant multiplied by the derivative:\n\n$$\\frac{d}{dx}[kf(x)] = k\\frac{d}{dx}f(x)$$\n\n✏️ **Example** \n\n\n---\n\n## {#diff-rules-3 data-menu-title=\"Rules for Differentiation (3)\"}\n\n[Rules for differentiation (3)]{.slide-title}\n\n<hr>\n\n**Constant Multiplier Rule**\n\nThe derivative of a constant $c$ multiplied by a function $f(x)$ is the same as the constant multiplied by the derivative:\n\n$$\\frac{d}{dx}[kf(x)] = k\\frac{d}{dx}f(x)$$\n\n ✏️ **Example**\n\n$$\ny=x^2+\\sqrt{2}x-\\frac{8}{x}+4\n$$\n\n---\n\n## {#logs-exp data-menu-title=\"Derivative of logs & exp\"} \n\n[Derivative of logs & exponents]{.slide-title}\n\n<hr>\n\n<br>\n\n[Two special derivatives:]{.body-text-l}\n\n<br>\n\n- [$\\frac{d}{dx}(e^x) = e^x$]{.body-text-l}\n\n<br>\n\n- [$\\frac{d}{dx}ln(x)=\\frac{1}{x}$]{.body-text-l}\n\n---\n\n## {#diff-rules-summary data-menu-title=\"Summary of differentiation rules\"}\n\n[Summary of differentiation rules]{.slide-title}\n\n<hr>\n\n<br>\n\n| Differentiation Rule | $f'(x)$ notation | $\\frac{d}{dx}$ notation |\n|----------------------|------------------|-------------------------|\n| **Constant Rule** | $f(x)=c \\Rightarrow f'(x)=0$ | $\\frac{d}{dx}[c]=0$ |\n| **Power Rule** | $f(x)=x^n \\Rightarrow f'(x)=n x^{n-1}$ | $\\frac{d}{dx}[x^n]=n x^{n-1}$ |\n| **Sum Rule** | $(g(x)+h(x))'=g'(x)+h'(x)$ | $\\frac{d}{dx}[g(x)+h(x)]=\\frac{d}{dx}g(x)+\\frac{d}{dx}h(x)$ |\n| **Difference Rule** | $(g(x)-h(x))' = g'(x)-h'(x)$ | $\\frac{d}{dx}[g(x)-h(x)]=\\frac{d}{dx}g(x)-\\frac{d}{dx}h(x)$ |\n| **Constant Multiplier Rule**  | $(c\\cdot g(x))'=c\\,g'(x)$ | $\\frac{d}{dx}[c\\,g(x)]=c\\,\\frac{d}{dx}g(x)$ |\n\n<br>\n\nAnd two special derivatives: $\\frac{d}{dx}(e^x) = e^x$ and $\\frac{d}{dx}ln(x)=\\frac{1}{x}$.\n\n:::{.center-text .body-text-s}\nThere's more differentiation rules (product, quotient, chain rule). \n\nThey're fun, but we won't be reviewing them.\n:::\n\n---\n\n## {#higher-order-der data-menu-title=\"Higher Order Derivatives\"}\n\n[Higher order derivatives]{.slide-title}\n\n<hr>\n\n- We can continue to take derivatives of derivatives.\n\n- The second derivative becomes the rate of change of the rate of change. \n\n- If we interpret the first derivative as velocity, then the second derivative is acceleration. \n\n. . .\n\n- Notation: \n\n    - Function: $f(x) = y$\n    - 1st derivative: $f'(x)$ or $\\frac{dy}{dx}$\n    - 2nd derivative: $f''(x)$ or $\\frac{d^2y}{dx^2}$\n    - nth derivative: $f^{(n)}(x)$ or $\\frac{d^ny}{dx^n}$\n\n---\n\n## {#derivatives-practice data-menu-title=\"Derivatives practice\"}\n\n[Derivatives practice]{.slide-title}\n\n<hr>\n\n[Solve individually and then check with a partner.]{style=\"color:green;\"}\n\n1) Which rules should you use to take these derivatives?\n\n$$\n\\begin{align}\n\\text{A)  }& f(x)=3x^4 &\\text{B) }  y=4x^2+3x-16\n\\end{align}\n$$\n\n2) Find the derivatives of these functions\n\n$$\n\\begin{align}\n&\\text{A) } y=3x^2 & &\\text{B) }h(x)=2x(x^2 + 3x) & &\\text{C) }g(y)=2\\sqrt{y} - e^y + 20\\ln(y)\n\\end{align}\n$$\n\n3) Find the 3rd derivative of:\n\n$$G(z)=3z^4-8z^3+2z-19$$\n\n---\n\n## {#derivatives-practice-solve-1 data-menu-title=\"Derivatives practice\"}\n\n[Derivatives practice]{.slide-title}\n\n<hr>\n\n[ ✏️  Let's see a solution!]{style=\"color:green;\"} \n\n2.B) Find the derivative $$h(x)=2x(x^2 + 3x)$$\n\n---\n\n## {#derivatives-practice-solve-2 data-menu-title=\"Derivatives practice\"}\n\n[Derivatives practice]{.slide-title}\n\n<hr>\n\n[ ✏️  Let's see a solution!]{style=\"color:green;\"} \n\n2.C) Find the derivative $$g(y)=2\\sqrt{y} - e^y + 20\\ln(y)$$\n\n---\n\n## {#derivatives-practice-solve-3 data-menu-title=\"Derivatives practice\"}\n\n[Derivatives practice]{.slide-title}\n\n<hr>\n\n[ ✏️  Let's see a solution!]{style=\"color:green;\"}\n\n3) Find the 3rd derivative of $G(z)=3z^4-8z^3+2z-19$.\n\n---\n\n## {#derivatives-solution data-menu-title=\"Derivatives solution\"}\n\n[Derivatives solution]{.slide-title}\n\n<hr>\n\n1) Which rules should you use to take these derivatives?\n\n$$\n\\begin{align}\n\\text{A)  }& f(x)=3x^4 &\\text{B) }  y=4x^2+3x-16\n\\end{align}\n$$\n\nA) Power Rule (with the Constant Multiplier Rule)\n\nB) Sum/Difference Rule, Power Rule, Constant Multiplier Rule, and Constant Rule (for $-16$)\n\n\n2) Find the derivatives of these functions\n\n$$\n\\begin{align}\n&\\text{A) } y=3x^2 & &\\text{B) }h(x)=2x(x^2 + 3x)\n\\end{align}\n$$\n\nA) $y' = 3\\cdot 2x^{(2-1)} = 6x$\n\nB) First expand: $h(x) = 2x\\cdot x^2 + 2x \\cdot 3x = 2x^3+6x^2$\n\nThen differentiate term by term: $h'(x) = 2\\cdot 3x^{(3-1)} + 6\\cdot 2x^{(2-1)} = 6x^2+12x$\n\n---\n\n## {#derivatives-solution-2 data-menu-title=\"Derivatives solution\"}\n\n[Derivatives solution]{.slide-title}\n\n<hr>\n\n2) Find the derivative of this function\n\n$$\ng(y)=2\\sqrt{y} - e^y + 20\\ln(y)\n$$\n\nRewrite $\\sqrt{y}$ as $y^{1/2}$:\n\n$$\n\\begin{align}\ng(y) &= 2y^{1/2}-e^y+20\\ln(y)\\\\\ng'(y) &= 2\\cdot\\frac{1}{2}y^{(1/2-1)} - e^y + 20\\cdot\\frac{1}{y}\\\\\n&= \\frac{1}{\\sqrt{y}} - e^y + \\frac{20}{y}\n\\end{align}\n$$\n\n---\n\n## {#derivatives-solution-3 data-menu-title=\"Derivatives solution\"}\n\n[Derivatives solution]{.slide-title}\n\n<hr>\n\n3) Find the 3rd derivative of:\n\n$$G(z)=3z^4-8z^3+2z-19$$\n\n$$\n\\begin{align}\nG'(z) &= 3\\cdot 4z^{(4-1)} - 8\\cdot 3z^{(3-1)} + 2\\cdot 1z^{(1-1)} - 0 = 12z^3-24z^2+2\\\\\nG''(z) &= 12\\cdot 3z^{(3-1)} - 24\\cdot 2z^{(2-1)} + 0 = 36z^2-48z\\\\\nG'''(z) &= 36\\cdot 2z^{(2-1)} - 48\\cdot 1z^{(1-1)} = 72z-48\n\\end{align}\n$$\n\n---\n\n## {#wrapping-up data-menu-title=\"Wrapping up\" background-color=\"#003660\"}\n\n<div class=\"page-center\">\n<div class=\"custom-subtitle\">Wrapping up...</div>\n</div>\n\n---\n\n## {#problem-set data-menu-title=\"Problem set\" }\n\n[Get some extra practice!]{.slide-title}\n\n<hr>\n\n<br>\n\n\n:::{.center-text}\n[**Problem set**](day4-problem-set.qmd)\n\n![](/notes/icons/homework.png){width=30%}\n\n:::\n\n---\n\n## {#what-we-covered data-menu-title=\"What we covered today\" }\n\n\n[What we covered today]{.slide-title}\n\n<hr> \n\n- <span style=\"color:#660099\"><b>↗️ Slope as a rate of change</b></span>  \n- <span style=\"color:#660033\"><b>🔎 Limits</b></span>  \n- <span style=\"color:#993300\"><b>🖊️ Derivatives and rate of change</b></span>  \n- <span style=\"color:#330000\"><b>🛤️ Tangent lines</b></span>  \n- <span style=\"color:#333300\"><b>📝 Rules for differentiation</b></span>  \n- <span style=\"color:#996600\"><b>🔹 Constant rule</b></span>  \n- <span style=\"color:#660000\"><b>💪 Power rule</b></span>  \n- <span style=\"color:#003300\"><b>➕ Sum and difference rule</b></span>  \n\n",
    "supporting": [
      "day4-slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}