---
format: 
  revealjs:
    chalkboard: false
    slide-number: true
    show-slide-number: print
    theme:
     - ../../ucsb-media.scss    
embed-resources: true
---

## Average slope

<hr>

```{r, fig.align='center'}

library(tidyverse)
library(latex2exp)

x=seq(-1,3,by=0.01)
y=x^2

lim_df<-data.frame(x=x,y=y)

dx=2
y2=y[which(lim_df$x==dx)]

slope=y2/dx
line=x*slope


ggplot(data=lim_df,aes(x=x,y=y))+
  geom_line(color="black", linewidth=3)+
  theme_classic()+
  annotate("point",x=0,y=0,size=6,color="blue")+
  theme(text = element_text(size = 28),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) + 
  coord_fixed(ratio = 1) +
  coord_cartesian(xlim=c(-1,3), ylim=c(0,8))
```

Start with:


<br>

Nearby point:

<br>

<br>

Average slope:


## Slide 1
```{r, fig.align='center'}

library(tidyverse)
x=seq(-1,3,by=0.01)
y=x^2

lim_df<-data.frame(x=x,y=y)

dx=2
y2=y[which(lim_df$x==dx)]

slope=y2/dx
line=x*slope


p0<-ggplot(data=lim_df,aes(x=x,y=y))+
  geom_line(color="black",linewidth=3)+
  theme_classic()+
  geom_line( data = data.frame(x = seq(-1, 3, by = 0.01),  
                               y = 1.5 * seq(-1, 3, by = 0.01)),
            aes(x = x, y = y),
            color="red",
            linewidth=2)+
  annotate("point",x=0,y=0,size=8,color="blue")+
  annotate("text", 
            x=0, y=1, 
            label="(x, f(x))",
            size=10,
            color="blue")+
  annotate("point",x=1.5, y=2.25, size=8, color="blue")+
  annotate("text", 
            x=2.25, y=2.25, 
            label="(x+Δx, f(x+Δx))",
            size=10,
            color="blue") +
  theme(text = element_text(size = 28),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) + 
  coord_fixed(ratio = 1) +
  coord_cartesian(xlim=c(-1,3), ylim=c(0,8))

p0
```

Start with a point $(x,f(x))$ on the graph. 

A nearby point can be $(x+\Delta x, f(x+\Delta x))$, where $\Delta x$ is a short distance from $x$. 


<br>

The average slope between $(x,f(x))$ and $(x+\Delta x, f(x+\Delta x))$ is given by

<span style="color:red">
$$\text{average slope} = \frac{f(x+\Delta x) - f(x)}{(x+\Delta x)-x} = \frac{f(x+\Delta x) - f(x)}{\Delta x}.$$
</span>


**What happens when $\Delta x$ becomes smaller and smaller?**

<!--
The slope of a line going through two points $(x_1,y_1)$ and $(x_2, y_2)$ is given by:

$$\text{slope}= \frac{y_2 - y_1}{x_2 - x_1} $$
-->

## Slide 2

```{r, fig.align='center'}
p1<-p0+
  geom_point(aes(x=dx,y=y2),color="blue",size=6)+
  geom_line(aes(x=x,y=line),color="red",linewidth=2)+
  annotate("text",x=1,y=7,label="Delta~x==2",parse=TRUE,size=14)+
  annotate("text",x=1,y=4.5,label="Slope=2",size=14)
p1

```

## Slide 3

```{r, fig.align='center'}
dx=1
y2=y[which(lim_df$x==dx)]

slope=y2/dx
line=x*slope
p2<-p0+
  geom_line(aes(x=x,y=line),color="red",linewidth=2)+
  geom_point(aes(x=dx,y=y2),color="blue",size=6)+
  annotate("text",x=1,y=7,label="Delta~x==1",parse=TRUE,size=14)+
  annotate("text",x=1,y=4.5,label="Slope=1",size=14)

p2

```

## Slide 4

```{r, fig.align='center'}
dx=0.5
y2=y[which(lim_df$x==dx)]

slope=y2/dx
line=x*slope
p3<-p0+
  geom_line(aes(x=x,y=line),color="red",linewidth=2)+
  geom_point(aes(x=dx,y=y2),color="blue",size=6)+
  annotate("text",x=1,y=7,label="Delta~x==0.5",parse=TRUE,size=14)+
  annotate("text",x=1,y=4.5,label="Slope=.25",size=14)
p3
```