{
  "hash": "660bf1aaa524cec5831b8870c27724b2",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat:\n  revealjs:\n    slide-number: true\n    # code-link: true\n    highlight-style: a11y\n    chalkboard: true\n    theme:\n      - ../../ucsb-media.scss\n    include-in-header:\n      text: |\n        <script>\n        (function loadCancelExtension(){\n          if (window.MathJax && window.MathJax.Hub) {\n            MathJax.Hub.Config({ TeX: { extensions: [\"cancel.js\"] } });\n          } else {\n            setTimeout(loadCancelExtension, 20);\n          }\n        })();\n        </script>\neditor_options:\n  chunk_output_type: console\n---\n\n## {#title-slide data-menu-title=\"Title Slide\" background=\"#053660\"}\n\n[Day 4: Bren Math Workshop]{.custom-title}\n\n<hr class=\"hr-teal\">\n\n[Carmen Galaz García, Ph.D.]{.body-text-l .center-text .baby-blue-text}\n\n[Bren School of Environmental Science & Management]{.center-text .body-text-m .baby-blue-text}\n\n<br>\n\n---\n\n## {#interpreting-slope data-menu-title=\"Interpreting the slope title\" background-color=\"#003660\"}\n\n\n<div class=\"page-center\">\n<div class=\"custom-subtitle\">Interpreting the slope</div>\n</div>\n\n---\n\n## {#avg-rate-of-change-blank data-menu-title=\"Slope (average)\"}\n\n[Slope (average)]{.slide-title}\n\n<hr>\n\n::::{.columns}\n:::{.column width=\"50%\"}\n\n::: {.body-text-m}\nSometimes, it can be useful to find the **average rate of change** of a function.\n:::\n\n✏️\n\n:::\n\n:::{.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-rates-of-change_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n::::\n\n---\n\n## {#avg-rate-of-change data-menu-title=\"Slope (average)\"}\n\n[Slope (average)]{.slide-title}\n\n<hr>\n\n::::{.columns}\n:::{.column width=\"50%\"}\n\n::: {.body-text-m}\nSometimes, it can be useful to find the **average rate of change** of a function.\n\nBetween any two points $(x_1,y_1)$ and $(x_2,y_2)$  on the graph of a function, the slope is found by:\n\n<br>\n\n$$m=\\frac{\\Delta y}{\\Delta x}=\\frac{y_2-y_1}{x_2-x_1}$$\n\nSame idea as in a line!\n:::\n\n:::\n\n:::{.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-rates-of-change_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n::::\n\n---\n\n## {#slope-roc data-menu-title=\"Slope represents rate of change\"}\n\n[Slope represents rate of change]{.slide-title}\n\n<hr>\n\nIce-core data before 1958. Mauna Loa data after 1958. \n\n![Source:[The Keeling Curve](https://keelingcurve.ucsd.edu)](../_linear-functions/images/loa.PNG)\n\n---\n\n## {#practice-out-loud data-menu-title=\"Practice out loud\"} \n\n[Get into the practice of saying the meaning out loud]{.slide-title3}\n\n<hr>\n\n- As if you're explaining it to someone unfamiliar with the data\n- Including units\n- Without overstating certainty \n\n[**For example:**]{.body-text-m} \n\n>\"Between 1972 and 2020 the price of hobbit homes increased by an average of $2,450 per year\" \n\n<br>\n\n*differs from*\n\n<br>\n\n>\"Between 1972 and 2020 the price of hobbit homes increased by $2,450 per year.\" \n\n---\n\n## {#slope-practice data-menu-title=\"Slope practice\"} \n\n[Slope practice]{.slide-title3}\n\n<hr>\n\n:::{style=\"color:green;\"}\n✏️ A city has begun a 20-day, round-the-clock grading and paving phase for a highway-widening project that cuts directly through a neighborhood. In response, a community air-quality monitoring group tracked the additional fine particulate matter concentration, $P(t)$ (µg/m³ of PM2.5 above baseline), in the neighborhood's air over the 20 days of that construction phase.\n:::\n\n:::: {.columns}\n::: {.column width=\"35%\"}\n\n:::{style=\"color:green;\"}\n| $t$ (days) | $P(t)$ (µg/m³) |\n|:---:|:---:|\n| 2  | 14.4 |\n| 6  | 33.6 |\n| 10 | 40.0 |\n| 14 | 33.6 |\n| 18 | 14.4 |\n:::\n:::\n\n::: {.column width=\"65%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-rates-of-change_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=95%}\n:::\n:::\n\n:::\n::::\n\n:::{style=\"color:green;\"}\na) Calculate the average rate of change in additional PM2.5 concentration between day 2 and day 6. Represent this graphically on the plot.\nb) Write your answer as a full sentence, with units, without overstating certainty.\n:::\n\n---\n\n## {#slope-practice-blank data-menu-title=\"Slope practice\"} \n\n[Slope practice]{.slide-title3}\n\n<hr>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n:::{style=\"color:green;\" }\n:::{.body-text-s}\n$P(t)$ measures µg/m³ of PM2.5 above baseline in the neighborhood's air over the 20 days of that construction phase.\n:::\n\n| $t$ (days) | $P(t)$ (µg/m³) |\n|:---:|:---:|\n| 2  | 14.4 |\n| 6  | 33.6 |\n| 10 | 40.0 |\n| 14 | 33.6 |\n| 18 | 14.4 |\n\n\na) Calculate the average rate of change in additional PM2.5 concentration between day 2 and day 6. Represent this graphically on the plot.\nb) Write your answer as a full sentence, with units, without overstating certainty.\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day4-rates-of-change_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=95%}\n:::\n:::\n\n✏️ \n\n:::\n\n:::\n\n---\n\n## {#slope-practice-solution data-menu-title=\"Slope practice\"} \n\n[Slope practice]{.slide-title3}\n\n<hr>\n\n<br>\n \n a)\n$$\n\\text{average rate of change} = \\frac{P(6) - P(2)}{6-2} = \\frac{33.6 - 14.4}{4} = \\frac{19.2}{4} = 4.8 \\ \\frac{\\mu\\text{g/m}^3}{\\text{day}}\n$$\n\n<br>\n\nb) Between day 2 and day 6 of the grading phase, additional PM2.5 concentration in the  neighborhood increased by an average of 4.8 µg/m³ per day.\n\n\n---\n\n## {#whole-story data-menu-title=\"Whole story\"} \n\n[The *average* slope of a continuous function rarely tells the whole story]{.slide-title3}\n  \n<hr>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/cod_graph.jpg){fig-align='center' width=100%}\n:::\n:::\n\n\n\n---\n\n## {#slope-avg cdata-menu-title=\"can be average or instantaneous\"}\n\n[Slope can be *average* or *instantaneous*]{.slide-title}\n\n<hr>\n\n::::{.columns}\n:::{.column width=\"50%\"}\n\n\n- Rise over run can always be used to find average rate of change between two parts of a graph\n\n\n:::\n\n:::{.column width=\"50%\"}\n\n- Instantaneous rate of change leads us to ✨calculus✨.\n\n:::\n::::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/trex.PNG){fig-align='center' width=50%}\n:::\n:::\n\n",
    "supporting": [
      "day4-rates-of-change_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}